# .github/release.yml

changelog:
  exclude:
    labels:
      - admin
  categories:
    - title: Enhancements
      labels:
        - enhancement
    - title: Corrections
      labels:
        - bug
    - title: Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
