# .github/release.yml

changelog:
  exclude:
    labels:
      - admin
  categories:
    - title: Enhancements
      labels:
        - enhancement
    - title: Bugfixes
      labels:
        - bugfix
    - title: Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
