# .github/release.yml

changelog:
  exclude:
    labels:
      - admin
      - meeting
  categories:
    - title: MLPro-SL - Supervised Learning
      labels:
        - SL
      exclude:
        labels:
          - documentation
    - title: MLPro-RL - Reinforcement Learning
      labels:
        - RL
      exclude:
        labels:
          - documentation
    - title: MLPro-GT - Game Theory
      labels:
        - GT
      exclude:
        labels:
          - documentation
    - title: MLPro-OA - Online Adaptivity
      labels:
        - OA
      exclude:
        labels:
          - documentation
    - title: MLPro-BF - Basic Functions
      labels:
        - BF
      exclude:
        labels:
          - documentation
    - title: Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
