# .github/release.yml

changelog:
  exclude:
    labels:
      - admin
      - meeting
  categories:
    - title: Enhancements MLPro-SL
      labels:
        - SL
    - title: Enhancements MLPro-RL
      labels:
        - RL
    - title: Enhancements MLPro-GT
      labels:
        - GT
    - title: Enhancements MLPro-OA
      labels:
        - OA
    - title: Enhancements MLPro-BF
      labels:
        - BF
    - title: Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
