name: Add issues to project MLPro

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issues to project MLPro
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@RELEASE_VERSION
        with:
          # You can target a project in a different organization
          # to the issue
          project-url: https://github.com/orgs/fhswf/projects/11
          github-token: ${{ secrets.ISSUE_UPDATES }}
          # labeled: bug, needs-triage
          # label-operator: OR