# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: python

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_run:
    workflows: ["Autodoc Gen"]
    types:
      - completed

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
    - name: Checkout Codes
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install numpy
        pip install matplotlib
        pip install dill
        pip install multiprocess
        pip install stable-baselines3
        pip install PettingZoo
        pip install gym==0.25.0
        pip install pyglet
        pip install pymunk
        pip install pygame
        pip install sphinx
        pip install sphinx-rtd-theme
        pip install sphinx-copybutton
        pip install hyperopt
        pip install optuna
        pip install transformations
        pip install scikit-learn
        pip install river
        pip install openml
    - name: Pip Freeze
      run: |
        pip freeze
    - name: Test with pytest
      run: |
        make pytest
