# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: docsgen

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Codes
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install numpy
        pip install matplotlib
        pip install gym
        pip install PettingZoo
        pip install stable-baselines3
        pip install pyglet
        pip install pymunk
        pip install pygame
        pip install sphinx
        pip install sphinx-rtd-theme
    - name: Build the Documentation
      run: |
        cd doc/rtd
        make html 
    
    - name: Check for modified files
      id: git-check
      run: echo ::set-output name=modified::$(if [ $(git diff-index HEAD | wc -l) -eq 1 ]; then echo "false"; else echo "true"; fi)

    - name: Push changes
    - uses: stefanzweifel/git-auto-commit-action@v4
        if: steps.git-check.outputs.modified == 'true'
        with:
          commit_message: Automated Documentation