name: Marketplace Update

on:
  schedule:
    - cron: '00 22 * * *'

  workflow_dispatch:

jobs:
  update-marketplace:
    name: Update the MLPro marketplace
    runs-on: ubuntu-latest

    steps:
      - name: Update marketplace
        uses: actions/checkout@v4
      - run: python3 ${GITHUB_WORKSPACE}/marketplace/update_marketplace.py
      # - run: echo ${GITHUB_WORKSPACE}
      # - run: ls -l ${GITHUB_WORKSPACE} > output.txt
      # - run: cat output.txt