name: Marketplace Update

on:
  schedule:
    - cron: '00 22 * * *'

  workflow_dispatch:

jobs:
  update-marketplace:
    name: Update the MLPro marketplace
    runs-on: ubuntu-latest

    steps:
      - name: Update marketplace
        uses: actions/checkout@v4
      - run: |
          pip3 install dill
          pip3 install mlpro
          pip3 install PyGithub
          python3 ${GITHUB_WORKSPACE}/marketplace/update_marketplace.py ${{ secrets.MARKETPLACE_UPDATE_TOKEN }} ../doc/rtd/content/04_marketplace/

          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
        
