name: Marketplace Update

on:
  schedule:
    - cron: '00 22 * * *'

  workflow_dispatch:

jobs:
  update-marketplace:
    name: Update the MLPro marketplace
    runs-on: ubuntu-latest

    steps:
      - run: python3 /home/runner/work/MLPro/marketplace/update_marketplace.py